# Generated by Django 5.1 on 2024-09-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="my_articles",
            field=models.ManyToManyField(
                blank=True, related_name="Articles_by_user", to="api.article"
            ),
        ),
    ]
