# Generated by Django 5.1 on 2024-09-22 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_extendeduser_my_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="liked_articles",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to="api.article"
            ),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="shared_articles",
            field=models.ManyToManyField(
                blank=True, related_name="shared", to="api.article"
            ),
        ),
    ]
