# Generated by Django 5.1 on 2024-09-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_article_likes_extendeduser_liked_articles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience", models.TextField()),
                ("education", models.TextField()),
                ("skills", models.TextField()),
                ("isExperiencePublic", models.BooleanField()),
                ("isEducationPublic", models.BooleanField()),
                ("isSkillsPublic", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="personal_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="further_details",
                to="api.personaldetails",
            ),
        ),
    ]
