# Generated by Django 5.1 on 2024-09-26 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_personaldetails_extendeduser_personal_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="request_from_others",
            field=models.ManyToManyField(
                blank=True,
                related_name="follow_from_others",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
