# Generated by Django 5.1 on 2024-09-26 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_extendeduser_request_from_others"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("follow_request", "New Follow Request"),
                            ("new_like", "New Like"),
                            ("new_comment", "New Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("type_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="request_to_others",
            field=models.ManyToManyField(
                blank=True, related_name="follow_to_others", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="notifications",
            field=models.ManyToManyField(
                blank=True, related_name="notifications", to="api.notifications"
            ),
        ),
    ]
