# Generated by Django 5.1 on 2024-09-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_notifications_extendeduser_request_to_others_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendeduser",
            name="shared_articles",
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("company", models.TextField()),
                ("location", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "full time job"),
                            ("part_time", "part time job"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_skills", models.TextField()),
                ("requested_education", models.TextField()),
                ("general_information", models.TextField()),
                (
                    "applicants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_aplicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
