# Generated by Django 5.1 on 2024-09-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_extendeduser_shared_articles_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="applications",
            field=models.ManyToManyField(
                blank=True, related_name="applications", to="api.jobs"
            ),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="my_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="Jobs_by_user", to="api.jobs"
            ),
        ),
    ]
