# Generated by Django 5.1 on 2024-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_extendeduser_applications_extendeduser_my_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="article_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="my_comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments_by_user", to="api.comment"
            ),
        ),
    ]
