# Generated by Django 5.1 on 2024-09-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_comment_article_id_extendeduser_my_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="username",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
